## Week 2 of Python tutorials - Vaibhav Beohar 
#### class of June 5th 2020
--> NumPy operations

NumPy multidimensional array slicing:

https://medium.com/@melodyxu/the-confusing-double-colon-in-numpy-850093adc36f

https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/

Other documentation

https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html


# Introduction to NumPy (Numerical Python)

## Overview
* NumPy is the fundamental package for scientific computing with Python
  * See the [NumPy Home Page](http://www.numpy.org/)
  
### Do Now!
* Import NumPy
* View the NumPy help page

In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

## NumPy is huge!
* Development of NumPy started in the mid-90s
* See the Wikipedia article on [NumPy's history](https://en.wikipedia.org/wiki/NumPy#History) for details


## About *ndarray*
* NumPy provides the class *ndarray*
* This contain single dimensional and multidimensional arrays
## *ndarray*s vs. *list*s and *array.array*s
* Compared to *list*s, *ndarray*s are:
  * more space efficient
  * less flexible
    * *list*s can hold heterogeneous data
  * more performant
  * able to be used to solve the same type of problems
    * *list*s and *ndarray*s can hold data in multidimensions

* Compared to *array.array*s, *ndarray*s are: 
  * similar in space efficiency
  * identical in requiring data to be homogeneous
  * similar in their run-time performance
  * able to be used with more general problems
    * *array.array*s can hold data in only one dimension

In [4]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

## What can be done with Arrays?
* Arrays can be: 
  * Created
  * Manipulated (Joining, Spliting, Shaping, etc.)
  * Accessed one element at a time
  * Accessed via array slices
  * Reshaped
  * Split
  * Concatenated

# Creating Arrays

## Using the *array* Function to Create *ndarrays*
* Although it is possible to create an *ndarray* instance using \_\_new\_\_(), it is not the recommended approach
* The factory methods *array*, *zeros*, *ones*, and *empty* are preferred
* The *array* factory method is discussed here

### Do Now!
* Import numpy
* View the doc string of the numpy array function

In [5]:
import numpy as np

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

## The array function will copy the source collection into a numpy array object and automatically determine the data type

In [8]:
data1 = [1, 2, 3, 4]
array1 = np.array(data1)
print(array1)
print(type(array1)) #this tells what the type of array1 is -- which is implicitly an ndarray
print(array1.dtype) #this tells what the dtype is of the individual elements inside ndarray


[1 2 3 4]
<class 'numpy.ndarray'>
int64


## Since there is a single float in this collection it determines that is the most appropriate data type for the numpy array

In [10]:
data2 = [1.0, 2, 3, 4]
array2 = np.array(data2)
print(array2)
print(array2.dtype)


[1. 2. 3. 4.]
float64


## You can specify the dtype parameter to force a preferred data type

In [12]:
data3 = [1, 2, 3, 4]
array3 = np.array(data3, dtype = float)
array3 = np.array(data3, dtype = np.int32)

print(array3)
print(array3.dtype)


[1 2 3 4]
int32


In [30]:
from numpy import int32, float32
d3 = [1,2,3,4]
a3 = np.array(d3, dtype = float32)
print(a3)
print(a3.shape)
print(len(a3))

[1. 2. 3. 4.]
(4,)
4


## If the collection is a collection of other collections, it will create a multi-dimensional numpy array

In [8]:
data4 = [[1,2,3,4],[5,6,7,8]]  #this is a 2-d list -- numpy shows it as a 2x2 matrix
array4 = np.array(data4)
print(array4)
print(array4.dtype)
print(array4.shape)
print('printing length: ',len(array4)) #array 1st dimension
print(array4.size) #total number of elements irrespective of shape

print('\n***********\n')
d4 = [[[1,2,3,4] , [5,6,6,7]], [[1,2,3,4] , [5,6,6,7]]]
a4 = np.array(d4)
print(a4.shape)
print(len(a4)) #array 1st dimension
print(a4.size) #total number of elements irrespective of shape


[[1 2 3 4]
 [5 6 7 8]]
int64
(2, 4)
printing length:  2
8

***********

(2, 2, 4)
2
16


In [13]:
d4 = [[1,2,3,4] , 
      [5,6,6,7], 
      [
          [1,2,3,4] , 
          [5,
           [0,0,0],
           6,
           7
          ]
      ]
     ]
a4 = np.array(d4)
print(a4.shape)
print(len(a4)) #array 1st dimension
print(a4.size) #

print(a4.ndim)

(3,)
3
3
1


## Summary of useful *ndarray* attributes
* For convenience, here a list of *ndarray* attributes
* Given x = np.ones( (2,3,4,5), dtype='float128')
   * ndim, the number of dimensions; e.g., 4
   * shape, the size of each dimension; e.g., (2,3,4,5)
   * dtype, the data type of each element; e.g., np.float128
   * itemsize, the size of each element 
        * Determined by the dtype; e.g., 16 bytes
   * size, the total number of elements in the array
        * Determined by the product of the shape sizes; e.g., 2 \* 3 \* 4 \* 5 = 120
   * nbytes, the total size of the array
        * Determine by the product of size and itemsize; e.g., 120 * 16 = 1920
   * strides, the number of bytes traversed in order to move from element to element in one dimension or across dimensions

## Using the *zeros* Function to Create *ndarrays*
* The *zeros* function, as its name suggest, creates an *ndarray* containing all zeros
* Unlike the *array* function, *zeros* doesn't take source data
* *zeros* includes a *shape* parameter for specifying the dimensions of the created *ndarray*


In [26]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [34]:
c = np.array(range(10))
# np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
z1 = np.zeros(4)
o1 = np.ones((2,4)) #pass tuple inside the ones() to create a multidimensional array
e1 = np.empty((2,4))

print(z1)
print(o1)
print(e1)

z1[0] = 100
z1[-1] = 20
z1[1:3] = 30
print('\n')
z1[:] = 40
print(z1)
print('\n')
e1[0] = -2 #change all elements in that index
print(e1) 

[0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1.49166815e-154 -1.49166815e-154  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -1.49166815e-154  5.60597629e-309]]


[40. 40. 40. 40.]


[[-2.00000000e+000 -2.00000000e+000 -2.00000000e+000 -2.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -1.49166815e-154  5.60597629e-309]]


## LAB 1: ## 
#### 1.	Define an ndarray containing the integer numbers 0 to 9.
#### 2.	Print the type of the array to the console.
#### 3.	Print the following properties of the array:
    a.	ndim
    b.	shape
    c.	size
    
#### 4.	Define a 3 x 3 NumPy array containing all 1s of integer type and display it to the console.
#### 5.	Print the three properties of Step 3 on the array defined in Step 4.

<br>

<details><summary>Click for <b>code</b></summary>
<p>

```python
import numpy as np
a1 = np.arange(10)
print(a1)
print(a1.dtype, a1.ndim, a1.shape, a1.size)

a2 = np.ones((3,3), dtype='int32')
print(a2)
print(a2.dtype, a2.ndim, a2.shape, a2.size)

```
</p>
</details>

In [16]:
c1 = np.arange(10)
print(c1)
print(c1.ndim)
print(c1.shape)
print(c1.size)

c2 = np.ones((3,3), dtype='int')
print(c2.dtype)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)
10
int64


## Instead of using the python range function and converting it into a numpy array, you could directly create a numpy array using the arange function

In [17]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [18]:
print ("arange array = ", np.arange(5, 25, 4))

arange array =  [ 5  9 13 17 21]


### *np.linspace*
* View the doc string for *np.linspace*
* Print an array of 50 numbers spaced over the interval 1 to 25

In [19]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [20]:
print ("Evenly spaced array = ", np.linspace(1,25))

Evenly spaced array =  [ 1.          1.48979592  1.97959184  2.46938776  2.95918367  3.44897959
  3.93877551  4.42857143  4.91836735  5.40816327  5.89795918  6.3877551
  6.87755102  7.36734694  7.85714286  8.34693878  8.83673469  9.32653061
  9.81632653 10.30612245 10.79591837 11.28571429 11.7755102  12.26530612
 12.75510204 13.24489796 13.73469388 14.2244898  14.71428571 15.20408163
 15.69387755 16.18367347 16.67346939 17.16326531 17.65306122 18.14285714
 18.63265306 19.12244898 19.6122449  20.10204082 20.59183673 21.08163265
 21.57142857 22.06122449 22.55102041 23.04081633 23.53061224 24.02040816
 24.51020408 25.        ]


## You can add a simple scalar value to an array and it will have the effect of adding it to each elements
### Note the difference if you do a multiply operation to a python list instead

In [21]:
array1 = np.array([[1,2,3],[4,5,6]])
print(array1 + 10)

print(array1 * 10)

print([1, 2, 3] * 10)

print(array1 **2) #squaring each element of the array

[[11 12 13]
 [14 15 16]]
[[10 20 30]
 [40 50 60]]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[[ 1  4  9]
 [16 25 36]]


## Arrays of compatible shapes can also be operated on

In [26]:
print(array1 + array1)
print(array1 * array1)
array2 = np.array([10, 20, 30])
print(array1 * array2)

# This is the wrong shape
# array3 = np.array([10, 20])
# print(array1 * array3)

array4 = np.array([[10], [20]])

print('\n')
print('array1: \n', array1)
print('array4: \n', array4)
print(array1 * array4)


[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[ 10  40  90]
 [ 40 100 180]]


array1: 
 [[1 2 3]
 [4 5 6]]
array4: 
 [[10]
 [20]]
[[ 10  20  30]
 [ 80 100 120]]


## Slicing is similar to how it behaves in a python collection with a few twists

In [28]:
array1 = np.arange(12)

print(array1)
print(array1[2])
print(array1[2:5])
array1[2:5] = 99
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
2
[2 3 4]
[ 0  1 99 99 99  5  6  7  8  9 10 11]


## When you have a multi-dimensional array it can start to be a bit different

In [47]:
array2d = np.array([[1,2],[3,4],[5,6]])
print(array2d)
print(array2d[1])      # returns the entire second element --> [3,4]
print(array2d[1][0])   # returns the second elements then takes the first element of that
print(array2d[1,0])    # returns the element at second row first column

print('\n interesting: \n', array2d[0:2,1])  # returns first two rows, and then 2nd column of each of those rows
print('\n interesting: \n', array2d[0:2][0]) # returns the first two rows, then removes 2nd row to leave only 1st row
print('\n')
print(array2d[0:2,0])  # returns the slice of the first two rows and the first column of each of those rows


a2d = np.array([[1,2,10],[3,4,20],[5,6,30]])
print(a2d[::2,-2::2])

[[1 2]
 [3 4]
 [5 6]]
[3 4]
3
3

 interesting: 
 [2 4]

 interesting: 
 [1 2]


[1 3]
[[2]
 [6]]


In [40]:
y = [1,2,3,4,5,6]
print(y[2:6:3])

print( y[::-1])

[3, 6]
[6, 5, 4, 3, 2, 1]


In [61]:
a1 = np.arange(36).reshape((6,6))
print(a1[:,:])
print('\n')
print(a1[::-6, ::-5])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[[35 30]]


## You can reshape arrays from one to two dimensions and vice versa so long as the dimensions make sense for the number of elements in the array

In [66]:
array1 = np.arange(20).reshape((4,5))
print(array1)
array2 = array1.reshape(20)
print(array2)
array3 = array1.reshape(2,10)
print(array3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [69]:
array1 = np.arange(20).reshape((4,5))
print(array1[:, ::-1]) #reverse all columns - but get all the rows 
print(array1[:, :3])

print(array1[:,::-1][:,:3]) #give all the rows but give the columns in descending order, 
                            #but 2nd matrix would be to get the top 3 columsn from that 1st matrix

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]
[[ 4  3  2]
 [ 9  8  7]
 [14 13 12]
 [19 18 17]]


## You can flatten an array to one dimension with either ravel or flatten. Ravel only makes a copy if necessary whereas flatten always makes a copy

In [70]:
array3 = array1.ravel()
print(array3)
array4 = array1.flatten()
print(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Transposing is the process of flipping an array 90 degrees and is easy to do in numpy

In [71]:
print(array1)
print(array1.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [79]:
print(array1)
print(array1.sum())

print('\n some more ops  -->', array1.sum(), '\n cumsum --> ', array1.cumsum())

print(np.sum(array1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
190

 some more ops  --> 190 
 cumsum -->  [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
190
[30 34 38 42 46]
[10 35 60 85]


In [86]:
print(array1.sum(axis=None)) #summing everything up

190


In [84]:
print(array1.sum(axis=0)) #columnwise sum - returns list with only 1d

[30 34 38 42 46]


In [85]:
print(array1.sum(axis=1)) #rowsum - returns list with only 1d

[10 35 60 85]


## LAB 2: ## 
#### 1.	Define a 3 x 3 array with the integers 1 through 9 named array1.
#### 2.	Define a second 3 x 3 array with the number 2 in each cell named array2.
#### 3.	Now, perform the following operations using the two arrays:
    a.	array1+array2
    b.	array1-array2
    c.	array1/array2
    d.	array1*5
#### 4.	Print elements 4 to 6 of array 1 using a slice operation.
#### 5.	Create a new single-dimensioned array named array3 with the numbers 0 through 19 in it.
#### 6.	Take a slice of elements 5 to 15 of array 3 and assign the slice to a variable named aslice and print the variable.
#### 7.	Modify the contents of the first and last elements of the slice by writing the value 99 into these elements.
#### 8.	Print the contents of the slice aslice and the array array3. Are the contents what you expect of both arrays?
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Use empty to create an array and set all values to 2 using a slice syntax. Make sure to use integers data types.
<br>
To set the elements from the right of a slice use negative numbers. Don't forget the index starts at zero on the left.
<br>
<br>
</p>
</details>


<details><summary>Click for <b>code</b></summary>
<p>

```python
array1 = np.arange(1, 10).reshape((3,3))
print(array1)
array2 = np.empty((3,3), dtype='int32')
array2[:] = 2
print(array2)

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 + 5)

print(array1.reshape((9,))[4:6])

array3 = np.arange(0, 20)
aslice = array3[5:15]
print(aslice)
aslice[0] = 99
aslice[-1] = 99
print(aslice)
print(array3)
```
</p>
</details>

In [110]:
array1 = np.linspace(1,9,9, dtype=int).reshape((3,3))
array2 = np.ones(9, dtype=int).reshape((3,3)) * 2


print(array1)
print(array2)


print(array1+array2)
print(array1-array2)
print(array1/array2)
print(array1*5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [113]:
#Print elements 4 to 6 of array 1 using a slice operation
print(array1.reshape(9,)[4:7])

[5 6 7]


In [ ]:
#Create a new single-dimensioned array named array3 with the numbers 0 through 19 in it

## You can read and write from files into numpy arrays

In [114]:
array1 = np.arange(10)
np.save('array1.npy', array1)
array2 = np.load('array1.npy')
print(array2)
! cat array1.npy

[0 1 2 3 4 5 6 7 8 9]
�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (10,), }                                                           
	

## File archives allow you to store multiple numpy arrays into one file. It's sort of like a saved dictionary

In [115]:
array1 = np.arange(10)
array2 = 2 * array1
np.savez('array_archive.npz', data_set_1=array1, data_set_2=array2)
archive = np.load('array_archive.npz')
print(archive['data_set_1'])
print(archive['data_set_2'])

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


## If you want to read or write from plain text files instead of the numpy serialized file format, there is another set of methods for that

In [63]:
array2d = np.array([[1,2,3],[4,5,6]])
np.savetxt('array_data.txt', array2d, delimiter=',')
array2d_from_file = np.loadtxt('array_data.txt', delimiter=',')
print(array2d_from_file)
! cat array_data.txt

[[1. 2. 3.]
 [4. 5. 6.]]
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00


## With NumPy, multiplying two two-dimensional arrays with * is an element-wise product, not a matrix dot product

In [62]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[1,2,3],[4,5,6]])
array_multiply = array1 * array2
print(array_multiply)

[[ 1  4  9]
 [16 25 36]]


## The dot method will do the cross multiply dot product used in a lot of complex algorithms

In [64]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[1,2],[3,4],[5,6]])
array_dot_product = array1.dot(array2)
print(array_dot_product)

[[22 28]
 [49 64]]


## Examples of random number generation

In [66]:
print (np.random.normal(5, 2, 9)) # mean = 5, std = 2
print (np.random.uniform(1, 100, 8)) # low = 1, high = 100
print (np.random.poisson(10, 10)) # 10 numbers averaging to 10

[5.51213695 5.81619289 2.69916571 4.30876555 6.34656609 6.47293363
 2.04712626 6.03094146 0.45704609]
[97.5616843  44.71475581 44.50379905  7.44001014 54.60145994 69.60775642
 94.00365986 40.68348883]
[12 19  8 14 10 11 10  8  9  7]


## Sometimes a function does not have a dtype parameter directly, but you can use the astype method to cast it to what you want

In [67]:
array1 = np.random.uniform(1, 100, 8)
print(array1)
array2 = array1.astype(int)
print(array2)

[90.05909083 16.91326258 71.2623461   9.11668008 63.3169145   5.89652345
 12.43456287 93.00602591]
[90 16 71  9 63  5 12 93]


In [70]:
np.random.seed(1)
print(np.random.uniform(1, 100, 8).astype(int))

[42 72  1 30 15 10 19 35]


## Homework: ## 
#### 1.	Generate 20 random integers between 1 and 100
#### 2.	Print the mean of those numbers
#### 3.	Turn those 20 numbers into a 4 x 5 matrix
#### 4. Transpose the matrix into a new variable
#### 5.	Find the dot product of the matrix and its transposed version
#### 6. Solve the simultaneous equations:
     10x + 20y = 50
     30x + 40y = 60
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Look at help on np.random. There are more choices than what we did in the slides.
<br>
To solve simultaneous equations look at np.linalg.solve
<br>
<br>
</p>
</details>



In [80]:
a1 = np.random.uniform(1, 100, 20).astype(int)
print(a1)

[36 44 70  6 67 67 21 13 32 37 57 44 98 11 21 16 65 26 47 25]


In [79]:
print(a1.mean())

56.8


In [82]:
b1 = a1.reshape((4,5))
print(b1)

[[36 44 70  6 67]
 [67 21 13 32 37]
 [57 44 98 11 21]
 [16 65 26 47 25]]


In [84]:
c1 = b1.T
print(c1)

[[36 67 57 16]
 [44 21 44 65]
 [70 13 98 26]
 [ 6 32 11 47]
 [67 37 21 25]]


In [86]:
d1 = b1.dot(c1)
print(d1)

[[12657  6917 12321  7213]
 [ 6917  7492  7146  5204]
 [12321  7146 15351  7362]
 [ 7213  5204  7362  7991]]


In [89]:
# https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

x_vars = [[10,20],[30,40]]
y_vars = [50, 60]

sol = np.linalg.solve(x_vars, y_vars)

print(sol)

[-4.   4.5]
